# Generated by Django 4.2.1 on 2023-05-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_list_productentry_product_list_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productentry',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productentry',
            old_name='product_list_id',
            new_name='product_list',
        ),
    ]
