# Generated by Django 4.2.1 on 2023-05-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_id_productentry_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
